### ISSUE TITLE
Musiclake手机端无法登录

### ISSUE THREAD

**Issue by JadeVane** [sunzongzheng/player-be#7]
之前 PC 端已经能正常登录使用了，但是 [musiclake](https://github.com/caiyonglong/MusicLake) 无法登录，在 musiclake 客户端选择 github 登录后会自动打开 chrome 以显示 github 登录框，登录完成后未正常跳转回 musiclake 客户端，在 chrome 上显示提示：

```
{"msg":"The redirect_uri MUST match the registered callback URL for this application.","log":{"name":"AuthorizationError","message":"The redirect_uri MUST match the registered callback URL for this application.","code":"redirect_uri_mismatch","uri":"https://docs.github.com/apps/managing-oauth-apps/troubleshooting-authorization-request-errors/#redirect-uri-mismatch","status":500}}
```

我看到 musiclake 项目中的 [相关项目|音乐API](https://github.com/caiyonglong/MusicLake#%E7%9B%B8%E5%85%B3%E9%A1%B9%E7%9B%AE%E9%9F%B3%E4%B9%90api) 显示 player-be 可作为云歌单 API，是否需要添加其他配置才能支持 musiclake 手机客户端的登录？

**Comment by sunzongzheng** [comment]
我记得安卓是自行嵌入SDK拿github的token，然后调`/auth/github/android`用github的token换musiclake的token，去安卓那个项目提issues问吧
