### ISSUE TITLE
pm2 start失败

### ISSUE THREAD

**Issue by Lancenas** [sunzongzheng/player-be#8]
#npm run start 启动正常，客户端可以正常登陆，查看云歌单

# pm2 start pm2.production.json

[PM2] Applying action restartProcessId on app [player-be-production](ids: [ 0, 2 ])
[PM2] Applying action restartProcessId on app [player-be-webhook-production](ids: [ 1 ])
[PM2] [player-be-webhook-production](1) ✓
[PM2] [player-be-production](0) ✓
[PM2] [player-be-production](2) ✓
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ player-be-product… │ cluster  │ 26   │ launching │ 0%       │ 0b       │
│ 2  │ player-be-product… │ cluster  │ 20   │ launching │ 0%       │ 0b       │
│ 1  │ player-be-webhook… │ fork     │ 1    │ online    │ 0%       │ 123.0mb  │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘

# pm2 list

┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ player-be-product… │ cluster  │ 30   │ errored   │ 0%       │ 0b       │
│ 2  │ player-be-product… │ cluster  │ 30   │ errored   │ 0%       │ 0b       │
│ 1  │ player-be-webhook… │ fork     │ 1    │ online    │ 0%       │ 119.7mb  │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘

客户端链接返回502

**Comment by sunzongzheng** [comment]
使用pm2查看下应用日志，
`pm2 log`

**Comment by Lancenas** [comment]
pm2卸载、重装后正常了
